import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

const NotePage: NextPage = () => {
  const router = useRouter();
  const notesId = router.query.id as string;

  const getNote = api.mynotes.getOneNote.useQuery({ id: notesId });
  const deleteNote = api.mynotes.deleteNote.useMutation({});
  const { data } = getNote;

  return (
    <>
      <Head>
        <title>Note Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data && (
        <div>
          <h1> title : {data?.title}</h1>
          <p> description : {data?.description}</p>
          <Link href={`edit/${notesId}`}>Edit Note</Link>
          <button
            onClick={() => {
              deleteNote.mutate({ id: notesId });
              router.push("/").catch((err) => console.log(err));
            }}
          >
            Delete
          </button>
        </div>
      )}
    </>
  );
};

export default NotePage;
