import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const getAllNotes = api.mynotes.allNotes.useQuery();
  const { data, isLoading } = getAllNotes;

  return (
    <>
      <Head>
        <title>Note App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-800">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Link
            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
            href="/newnote"
          >
            New Note
          </Link>
        </div>
        {data &&
          data.map((note, index) => {
            return (
              <div key={index}>
                <h2 className="text-white">
                  <Link href={note.id}>{note.title}</Link>
                </h2>
              </div>
            );
          })}{" "}
        {isLoading && <h1 className="text-white">Loading...</h1>}
      </main>
    </>
  );
};

export default Home;
