import { type NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import type { ChangeEvent, FormEvent } from "react";
import { useRouter } from "next/router";

// import Link from "next/link";

import { api } from "~/utils/api";

interface FormData {
  title: string;
  description: string;
}

const NewNote: NextPage = () => {
  const router = useRouter();
  const addNewNote = api.mynotes.newNote.useMutation({});
  const [formData, setFormData] = useState<FormData>({
    title: "",
    description: "",
  });

  const handleTitle = (event: ChangeEvent<HTMLInputElement>) => {
    setFormData({
      ...formData,
      title: event.target.value,
    });
  };
  const handleDescription = (event: ChangeEvent<HTMLTextAreaElement>) => {
    setFormData({
      ...formData,
      description: event.target.value,
    });
  };

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    addNewNote.mutate({
      title: formData.title,
      description: formData.description,
    });

    setFormData({
      title: "",
      description: "",
    });

    router.push("/").catch((err) => console.log(err));
  };

  return (
    <>
      <Head>
        <title>Create New Note</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-center bg-slate-800  px-96 text-red-300">
        <h1>Create new Note </h1>
        <br></br>
        <form
          className="flex flex-col justify-center"
          onSubmit={(e) => onSubmit(e)}
        >
          <label htmlFor="title">Title</label>
          <input
            className="bg-gray-100"
            type="text"
            name="title"
            id="title"
            required
            value={formData.title}
            onChange={(event) => handleTitle(event)}
          />
          <br></br>
          <label htmlFor="description">Description</label>
          <textarea
            className="bg-gray-100"
            name="description"
            id="description"
            required
            onChange={(event) => handleDescription(event)}
            value={formData.description}
          />

          <button type="submit">Submit</button>
        </form>
      </main>
    </>
  );
};

export default NewNote;
